### ISSUE TITLE
Explicit documentation of query parameters

### ISSUE THREAD

**Issue by bww** [instaunit/instaunit#7]
This would give us a bit more flexibility to render parameters usefully in all documentation types, as opposed to just punting to `doc`. Maybe something like:

```yaml
-
  params:
    first: Documentation for parameter `first`
    second: Documentation for parameter `second`
    # ...
```
